### PR TITLE
Fix some mistakes like 'cast from pointer to smaller type...' about t…

### PR DESCRIPTION
**Pull request by vufa**
…ype OMX::buffer_id in media/libstagefright/omx/OMXNodeInstance.cpp.

### CODE REVIEW

**Comment by ghost** [comment]
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/SoftVideoEncoderOMXComponent.cpp
frameworks/av/media/libstagefright/omx/OMXNodeInstance.cpp:1711:40: error: out-of-line definition of 'findBufferHeader' does not match any declaration in 'android::OMXNodeInstance'
OMX_BUFFERHEADERTYPE *OMXNodeInstance::findBufferHeader(OMX::buffer_id buffer) {
                                       ^~~~~~~~~~~~~~~~
1 error generated.

**Comment by Hikari-no-Tenshi** [comment]
@BlueGost try this: https://github.com/ResurrectionRemix-mtk/android_frameworks_av-rr/commit/bac6dbf9f076a0e7328fce39d7c4b15b38caf0ca

**Comment by ghost** [comment]
@Hikari-no-Tenshi ,Thank you very much, I'll try it next week!

**Comment by ghost** [comment]
@Hikari-no-Tenshi 
There are a new error happened:
external/sepolicy/Android.mk:84: recipe for target '/home/andriod/MX4/out/target/product/mx4/obj/ETC/sepolicy_intermediates/sepolicy' failed
make: **\* [/home/andriod/MX4/out/target/product/mx4/obj/ETC/sepolicy_intermediates/sepolicy] Error 1

The source code of external/sepolicy/Android.mk: line 84
$(LOCAL_BUILT_MODULE) : $(sepolicy_policy.conf) $(HOST_OUT_EXECUTABLES)/checkpolicy
    @mkdir -p $(dir $@)
    $(hide) $(HOST_OUT_EXECUTABLES)/checkpolicy -M -c $(POLICYVERS) -o $@ $<
    $(hide) $(HOST_OUT_EXECUTABLES)/checkpolicy -M -c $(POLICYVERS) -o $(dir $<)/$(notdir $@).dontaudit $<.dontaudit

**Pull request merged**
